# Generated by Django 4.0.2 on 2022-02-20 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('saf', 'SAF'), ('zabet', 'ZABET'), ('superzabet', 'SUPERZABET'), ('modeer', 'MODEER'), ('raeesarkan', 'RAEESARKAN')], default='saf', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.branches')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Report', max_length=300)),
                ('doc', models.FileField(upload_to='files/')),
                ('op1', models.FileField(blank=True, null=True, upload_to='files/')),
                ('op2', models.FileField(blank=True, null=True, upload_to='files/')),
                ('approved', models.BooleanField(default=False)),
                ('descr', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('sec_id', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docs', to='users.branches')),
                ('coming', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent', to='users.userdetail')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created', to='users.userdetail')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docs', to='users.userdetail')),
            ],
        ),
    ]
