# Generated by Django 4.0.2 on 2022-02-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='dep',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddocs', to='users.dep'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='dep',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dusers', to='users.dep'),
        ),
    ]
