# Generated by Django 4.0.2 on 2022-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userdetail_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
