# Generated by Django 4.0.2 on 2022-03-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='docs', to='users.userdetail'),
        ),
    ]
