# Generated by Django 4.0.2 on 2022-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_doc_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='rank',
            field=models.CharField(blank=True, choices=[('saf', 'SAF'), ('zabet', 'ZABET'), ('superzabet', 'SUPERZABET'), ('modeer', 'MODEER'), ('raeesarkan', 'RAEESARKAN')], max_length=100, null=True),
        ),
    ]
