# Generated by Django 4.0.2 on 2022-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdetail_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='imgmadany',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='rank',
            field=models.CharField(choices=[('saf', 'SAF'), ('zabet', 'ZABET'), ('superzabet', 'SUPERZABET'), ('modeer', 'MODEER'), ('raeesarkan', 'RAEESARKAN'), ('archive', 'ARCHIVE')], default='saf', max_length=100),
        ),
    ]
