# Generated by Django 4.0.2 on 2022-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdetail_imgmadany_alter_userdetail_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
