# Generated by Django 4.0.2 on 2022-06-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doc_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='imgmadany',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='rank',
            field=models.CharField(choices=[('Employee', 'EMPLOYEE'), ('Supervisor', 'SUPERVISOR'), ('Manager', 'Manager'), ('CTO', 'CTO'), ('CEO', 'CEO'), ('archive', 'ARCHIVE')], default='saf', max_length=100),
        ),
    ]
